### ISSUE TITLE
advanced usage example 

### ISSUE THREAD

**Issue by badiret** [P1umer/AFLplusplus-protobuf-mutator#1]
Hi, thanks for your code.
I am not that familiar with cpp to figure out some magic going on in the header file. I have few questions about how to use it.

Once the `TestMessageHandler::TransferMessageType` is called, the proto data has been already mutated or am I supposed to implement there my custom mutation logic?

From within the `TestMessageHandler::TransferMessageType` function how can I access the `max_size` variable that was passed to `afl_custom_fuzz` ?

thanks

**Comment by P1umer** [comment]
Hi, thanks for your question. The goal of `AFLplusplus-protobuf-mutator` is to make protobuf mutations more convenient in `afl++`。The library will automatically implement the mutation of protobuf, and users only need to convert the mutated proto into some more interesting data。To be more specific, the code after `DEFINE_AFL_PROTO_FUZZER` will be used as the function body of `ProtoToDataHelper`, and `ProtoToDataHelper` will rely on the `afl_custom_post_process` interface, which is provided by `afl++` and does not include `max_size` field。However, you can create a new field for `MutateHelper` and save the `max_size` in `MutateHelper` during the `afl_custom_fuzz` , which requires a bit of code modification.

**Comment by badiret** [comment]
Thanks for your prompt reply.
By printing `input.DebugString()` within the function `TestMessageHandler::TransferMessageType` then I should get different  values as result of the mutations that occurred, correct? 
I added that print but I always see the same values printed out.
thanks

**Comment by P1umer** [comment]
Oh，I think it may be a problem with the corpus. Can you provide more information about it？
thanks

**Comment by badiret** [comment]
Sure, following is `TransferMessageType` function:
```
size_t TestMessageHandler::TransferMessageType(const Root& input, unsigned char **out_buf){

    size_t mutated_size = input.ByteSizeLong();
    uint8_t* buffer = new uint8_t[mutated_size]; 
    if (!input.SerializeToArray(buffer, mutated_size)) {
        cerr << "Failed to write input." << endl;
        return -1;
    }
    *out_buf = buffer;
    return mutated_size;
}
```
Then, the harness is as following:
```
int main(int argc, char *argv[])
{
    Root output;
    char str[100]={};
    int *ptr = NULL;
    fstream iinput(argv[1], ios::in | ios::binary);
    if (!iinput) {
      cout << argv[1] << ": File not found.  Creating a new file." << endl;
			return -1;
    } else if (!output.ParseFromIstream(&iinput)) {
      cerr << "Failed to parse." << endl;
      return -1;
    }
	int val = output.test();
	fprintf(stdout,"val %d\n", val);
        return 0;
}
```
I run the fuzzer with the following script:
```
AFL_DISABLE_TRIM=1 \
AFL_CUSTOM_MUTATOR_ONLY=1 \
AFL_CUSTOM_MUTATOR_LIBRARY=./build/example/libtest-fuzzer.so \
AFL_SKIP_CPUFREQ=1 \
AFL_DEBUG=1 \
AFL_KEEP_TRACES=1 \
AFL_PRINT_FILENAMES=1 \
AFL_DEBUG_CHILD=1 \
AFL_NO_UI=1 \
$FUZZHOME/AFLplusplus/afl-fuzz -i ./in -o ./out -- ./build/example/harness/harness @@

```
The output printed by the harness shows very often the same value.
thanks


[edit] ps: I serialize a corpus with:
```
Root proto;
proto.set_test(666);
fstream output(argv[1], ios::out | ios::trunc | ios::binary);
proto.SerializeToOstream(&output);
```

**Comment by MatthewShao** [comment]
I met same problem here, I printed the output at the end of `A_CustomProtoMutator`, but the ouput did not change from time to time as expected.
```cpp
    size_t A_CustomProtoMutator(MutateHelper *m, bool binary, unsigned char *buf, size_t buf_size, 
                                unsigned char **out_buf, unsigned char *add_buf, 
                                size_t add_buf_size, size_t max_size, 
                                protobuf::Message* input1,
                                protobuf::Message* input2) {                   
        using libfuzzer::CustomProtoMutator;
        using libfuzzer::CustomProtoCrossOver; 

        // (PC) probability of crossover : 0.8 (0.6~1.0)
        // (PM) probability of mutation  : 0.2 
        switch (GetRandom(m->GetSeed())){
            case 1:
            case 2:{
                // 1. Realloc m.buf_ to meet length requirements and copy buf to m.buf_.
                //    In this case, We don’t need to allocate a separate outbuf for each
                //    execution of afl_custom_fuzz() but only realloc buf_ in MutateHelper.
                // 2. Mutate m.buf_ and store the length
                memcpy(m->ReallocBuf(std::max(max_size, buf_size)), buf, buf_size);
                m->SetLen(CustomProtoMutator(binary, m->GetOutBuf(), buf_size, max_size, 
                                             m->GetSeed(), input1));
                break;
            }
            default:{
                // Crossover buf and add_buf and store the outbuf to m.buf_
                m->ReallocBuf(std::max(max_size, std::max(buf_size, add_buf_size)));
                m->SetLen(CustomProtoCrossOver(binary, buf, buf_size, add_buf, add_buf_size, m->GetOutBuf(), 
                                               max_size,m->GetSeed(), input1, input2));
                break;
            }
        }
        
        *out_buf = m->GetOutBuf();
	 std::cout << "out:" << *out_buf << "\n"; // print the output, but did not change as expected
        return m->GetLen();
    }
```
@P1umer Could you please give some hints about this problem?
btw, I put a seed file in `in` dir looks like : `test: 123123123`, during the fuzz procedure, I think it should print various value for `test`, but sadly it remained as the same.

**Comment by P1umer** [comment]
Hello, this function `A_CustomProtoMutator` is actually a wrapper of `CustomProtoMutator`, so the mutation is implemented by LPM. You can check if `CustomProtoMutator` is working properly.

**Comment by MatthewShao** [comment]
I followed the code and finally found the reason. `CustomProtoMutator` will call `LLVMFuzzerMutate` here: https://github.com/google/libprotobuf-mutator/blob/a304ec48dcf15d942607032151f7e9ee504b5dcf/src/libfuzzer/libfuzzer_mutator.cc#L54-L56

`LLVMFuzzerMutate` will be linked to the actual implemention when it is running in libfuzzer, but it could not find the correct function in aflplusplus and will `return 0`. Therefore no mutation happens during the fuzzing.

**Comment by P1umer** [comment]
@MatthewShao Thanks a lot for your effort! We will prepare a CL for fixing this.

**Comment by P1umer** [comment]
Fixed in https://github.com/P1umer/AFLplusplus-protobuf-mutator/commit/af7a46022f1966333e2c43895c39a99b8c9c2d96.
